version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: hotel_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: hotel_testing
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - hotel_data:/var/lib/postgresql/data
  api:
    image: postgrest/postgrest:latest
    container_name: hotel_api
    environment:
      PGRST_DB_URI: postgres://admin:password123@db:5432/hotel_testing
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: admin
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  hotel_data: